---
stages:
  - build
  - deploy
  - release

.build:
  stage: build
  image:
    name: ghcr.io/puppeteer/puppeteer:latest
    entrypoint: [""]
  variables:
    PUPPETEER_SKIP_DOWNLOAD: "true"
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npx resumed validate resume.json
    - npx resumed render resume.json --theme jsonresume-theme-even --output resume.html
    - npx resumed export resume.json --theme jsonresume-theme-even --output resume.pdf
  artifacts:
    paths:
      - resume.html
      - resume.pdf

# Merge requests

ci:build:cv:
  extends: .build
  artifacts:
    expire_in: 1 week
    expose_as: generated cv
    paths:
      - resume.html
      - resume.pdf
  only:
    - merge_requests

# Default branch

build:cv:default:
  extends: .build
  only:
    - main

pages:
  stage: deploy
  image: alpine:latest
  needs:
    - build:cv:default
  script:
    - mkdir -p public
    - cp resume.html public/index.html
    - cp resume.pdf public/resume.pdf
  pages: true
  publish: public
  environment:
    name: pages
    url: https://pierre.guinoiseau.nz
  artifacts:
    paths:
      - public
  only:
    - main

# Tags / releases

build:cv:
  extends: .build
  only:
    - tags

release:
  stage: release
  image: python:3
  needs:
    - build:cv
  script:
    - pip3 install gitlab-release
    - gitlab-release --link-artifact resume.html resume.pdf
  artifacts:
    paths:
      - resume.html
      - resume.pdf
  only:
    - tags
